# main things to fix
#  - need way to specify scripts for different rules (eg scenarios, methods etc)
#  - need to find way to specify all the target files
#  - need to find way to set seeds

METHODS = ["mean","median"]

rule all:
    input: expand("score/rnorm/{method}/MSE/score.1.RDS",method=METHODS)
#"score/rnorm/mean/MSE/score.1.RDS", "score/rnorm/median/MSE/score.1.RDS" 

rule clean:
    shell: "rm -r meta; rm -r output; rm -r input; rm -r score"

rule run_scenario:
    output: "input/{scenario}/input.{seed}.RDS", "meta/{scenario}/meta.{seed}.RDS"
    shell: "Rscript R/scenarios/{wildcards.scenario}.R 1000 0 {output}"

rule run_method:
    input: "input/{scenario}/input.{seed}.RDS"
    output: "output/{scenario}/{method}/output.{seed}.RDS"
    shell: "Rscript R/methods/{wildcards.method}.R {input} {output}"

rule run_score:
    input: "output/{scenario}/{method}/output.{seed}.RDS", "meta/{scenario}/meta.{seed}.RDS"
    output: "score/{scenario}/{method}/{score}/score.{seed}.RDS"
    shell: "Rscript R/scores/{wildcards.score}.R {input} {output}"

