# main things to fix
#  - need way to specify scripts for different rules (eg scenarios, methods etc)
#  - need to find way to set seeds

SEEDS = [1,2,3,4,5]
SCENARIOS = ["rnorm","rt"]
METHODS = ["mean","median"]
SCORES = ["MSE"]

rule all:
    input: expand("score/{scenario}/{method}/{score}/score.{seed}.RDS",scenario=SCENARIOS,method=METHODS,score=SCORES,seed=SEEDS)

rule clean:
    shell: "rm -r meta; rm -r output; rm -r input; rm -r score"

rule run_scenario:
    output: "input/{scenario}/input.{seed}.RDS", "meta/{scenario}/meta.{seed}.RDS"
    shell: "Rscript R/scenarios/{wildcards.scenario}.R 1000 0 {output}"

rule run_method:
    input: "input/{scenario}/input.{seed}.RDS"
    output: "output/{scenario}/{method}/output.{seed}.RDS"
    shell: "Rscript R/methods/{wildcards.method}.R {input} {output}"

rule run_score:
    input: "output/{scenario}/{method}/output.{seed}.RDS", "meta/{scenario}/meta.{seed}.RDS"
    output: "score/{scenario}/{method}/{score}/score.{seed}.RDS"
    shell: "Rscript R/scores/{wildcards.score}.R {input} {output}"

